const inputCountryAnswer = (country) => {
	const el = document.querySelector('input');
	Object.getOwnPropertyDescriptor(Object.getPrototypeOf(el), 'value').set.call(el, country);
	el.dispatchEvent(new Event('input', {
		bubbles: true
	}));
}

const countriesTradle = {
	ago: "Angola",
	bdi: "Burundi",
	ben: "Benin",
	bwa: "Botswana",
	bfa: "Burkina Faso",
	caf: "Central African Republic",
	civ: "Cote d'Ivoire",
	cmr: "Cameroon",
	cod: "Democratic Republic of the Congo",
	cog: "Republic of the Congo",
	com: "Comoros",
	cpv: "Cape Verde",
	dji: "Djibouti",
	dza: "Algeria",
	egy: "Egypt",
	eri: "Eritrea",
	eth: "Ethiopia",
	swz: "Eswatini",
	gab: "Gabon",
	gha: "Ghana",
	gin: "Guinea",
	gmb: "Gambia",
	gnb: "Guinea-Bissau",
	gnq: "Equatorial Guinea",
	ken: "Kenya",
	lso: "Lesotho",
	lbr: "Liberia",
	lby: "Libya",
	mar: "Morocco",
	mdg: "Madagascar",
	mli: "Mali",
	moz: "Mozambique",
	mrt: "Mauritania",
	mus: "Mauritius",
	mwi: "Malawi",
	nam: "Namibia",
	ner: "Niger",
	nga: "Nigeria",
	rwa: "Rwanda",
	sdn: "Sudan",
	sen: "Senegal",
	shn: "Saint Helena",
	sle: "Sierra Leone",
	som: "Somalia",
	ssd: "South Sudan",
	stp: "Sao Tome and Principe",
	syc: "Seychelles",
	tcd: "Chad",
	tgo: "Togo",
	tun: "Tunisia",
	tza: "Tanzania",
	uga: "Uganda",
	zaf: "South Africa",
	zmb: "Zambia",
	zwe: "Zimbabwe",
	atf: "French South Antarctic Territory",
	afg: "Afghanistan",
	are: "United Arab Emirates",
	arm: "Armenia",
	aze: "Azerbaijan",
	bgd: "Bangladesh",
	bhr: "Bahrain",
	brn: "Brunei",
	btn: "Bhutan",
	cck: "Cocos (Keeling) Islands",
	chn: "China",
	cxr: "Christmas Island",
	cyp: "Cyprus",
	geo: "Georgia",
	hkg: "Hong Kong",
	idn: "Indonesia",
	ind: "India",
	iot: "British Indian Ocean Territory",
	irn: "Iran",
	irq: "Iraq",
	isr: "Israel",
	jor: "Jordan",
	jpn: "Japan",
	kaz: "Kazakhstan",
	kgz: "Kyrgyzstan",
	khm: "Cambodia",
	kor: "South Korea",
	kwt: "Kuwait",
	lao: "Laos",
	lbn: "Lebanon",
	lka: "Sri Lanka",
	mac: "Macau",
	mdv: "Maldives",
	mmr: "Burma",
	mng: "Mongolia",
	mys: "Malaysia",
	npl: "Nepal",
	omn: "Oman",
	pak: "Pakistan",
	phl: "Philippines",
	prk: "North Korea",
	pse: "Palestine",
	qat: "Qatar",
	sau: "Saudi Arabia",
	sgp: "Singapore",
	syr: "Syria",
	tha: "Thailand",
	tjk: "Tajikistan",
	tkm: "Turkmenistan",
	tls: "Timor-Leste",
	tur: "Turkey",
	uzb: "Uzbekistan",
	vnm: "Vietnam",
	xxb: "Other Asia",
	yem: "Yemen",
	alb: "Albania",
	and: "Andorra",
	aut: "Austria",
	bgr: "Bulgaria",
	bih: "Bosnia and Herzegovina",
	blr: "Belarus",
	bel: "Belgium",
	lux: "Luxembourg",
	che: "Switzerland",
	cze: "Czechia",
	deu: "Germany",
	dnk: "Denmark",
	esp: "Spain",
	est: "Estonia",
	fin: "Finland",
	fra: "France",
	gbr: "United Kingdom",
	gib: "Gibraltar",
	grc: "Greece",
	hrv: "Croatia",
	hun: "Hungary",
	irl: "Ireland",
	isl: "Iceland",
	ita: "Italy",
	ltu: "Lithuania",
	lva: "Latvia",
	mda: "Moldova",
	mkd: "North Macedonia",
	mlt: "Malta",
	mne: "Montenegro",
	nld: "Netherlands",
	nor: "Norway",
	pol: "Poland",
	prt: "Portugal",
	rou: "Romania",
	rus: "Russia",
	smr: "San Marino",
	srb: "Serbia",
	svk: "Slovakia",
	svn: "Slovenia",
	swe: "Sweden",
	ukr: "Ukraine",
	yug: "Yugoslavia",
	abw: "Aruba",
	aia: "Anguilla",
	ant: "Netherlands Antilles",
	atg: "Antigua and Barbuda",
	bes: "Bonaire",
	bhs: "Bahamas",
	blm: "Saint Barthélemy",
	blz: "Belize",
	bmu: "Bermuda",
	brb: "Barbados",
	can: "Canada",
	cri: "Costa Rica",
	cub: "Cuba",
	cuw: "Curaçao",
	cym: "Cayman Islands",
	dma: "Dominica",
	dom: "Dominican Republic",
	grd: "Grenada",
	grl: "Greenland",
	gtm: "Guatemala",
	hnd: "Honduras",
	hti: "Haiti",
	jam: "Jamaica",
	kna: "Saint Kitts and Nevis",
	lca: "Saint Lucia",
	maf: "Saint Maarten",
	mex: "Mexico",
	msr: "Montserrat",
	nic: "Nicaragua",
	pan: "Panama",
	slv: "El Salvador",
	spm: "Saint Pierre and Miquelon",
	tca: "Turks and Caicos Islands",
	tto: "Trinidad and Tobago",
	usa: "United States",
	vct: "Saint Vincent and the Grenadines",
	vgb: "British Virgin Islands",
	asm: "American Samoa",
	aus: "Australia",
	cok: "Cook Islands",
	fji: "Fiji",
	fsm: "Micronesia",
	gum: "Guam",
	kir: "Kiribati",
	mhl: "Marshall Islands",
	mnp: "Northern Mariana Islands",
	ncl: "New Caledonia",
	nfk: "Norfolk Island",
	niu: "Niue",
	nru: "Nauru",
	nzl: "New Zealand",
	pcn: "Pitcairn Islands",
	plw: "Palau",
	png: "Papua New Guinea",
	pyf: "French Polynesia",
	slb: "Solomon Islands",
	tkl: "Tokelau",
	ton: "Tonga",
	tuv: "Tuvalu",
	vut: "Vanuatu",
	wlf: "Wallis and Futuna",
	wsm: "Samoa",
	arg: "Argentina",
	bol: "Bolivia",
	bra: "Brazil",
	chl: "Chile",
	col: "Colombia",
	ecu: "Ecuador",
	flk: "Falkland Islands",
	guy: "Guyana",
	per: "Peru",
	pry: "Paraguay",
	sur: "Suriname",
	ury: "Uruguay",
	ven: "Venezuela"
}

const country = /export\/([a-z]{3})/.exec(document.querySelector('iframe').src)[1];
inputCountryAnswer(countriesTradle[country]);